/**
 * 英文-美国，语言文件
 */
define(function(){
	var English = {
		boarding_gate:'boarding gate',
		Seat_number:'Seat number',
		myFlight:'myFlight',
		historyFlight:'historyFlight',
		
		
		//舱位类型
		cabinType:{A:'All',F:'First',C:'Business',Y:'Economy','0':'premium'},//'0':'Economy plus'
		selectCabin:'Select Class',
		//周
		week:['Sunday','Monday','Tuesday ','Wednesday ','Thursday','Friday','Saturday'],
		short_week:["Sun.","Mon.","Tue.","Wed.","Thu.","Fri.","Sat."],
		hotelshort_week:["Sun,","Mon,","Tue,","Wed,","Thu,","Fri,","Sat,"],
		ok:'ok',
		cancel:'cancel',
		//航空公司
		airline_list:{
			'3U':'Sichuan',
			'8C':'Shanxi',
			'8L':'Yunnan Lucky',
			'CA':'Air China',
			'9C':'Spring',
			'CN':'Grand China',
			'CZ':'China Southern',
			'EU':'Chengdu',
			'FM':'Shanghai',
			'G8':'Great Wall',
			'HO':'Ji Xiang',
			'HU':'Hainan',
			'JD':'Deer Air',
			'JR':'Joy Air',
			'KN':'China United',
			'MF':'Xiamen',
			'MU':'China Eastern',
			'SC':'Shandong',
			'SZ':'Southwest',
			'WH':'Northwest',
			'WU':'Wuhan',
			'XO':'Xinjiang',
			'ZH':'Shenzhen',
			'PN':'West Air',
			'BK':'OK Air',
			'G5':'China Express',
			'GS':'Tianjin',
			'KY':'Kunming',
			'TV':'Tibet',
			'CJ':'Northern',
			'3Q':'Yunnan',
			'GB':'Greatwall',
			'NS':'Northeast',
			'OQ':'Chongqing',
			'VD':'Kunpeng',
			'HX':'Hongkong',
			'DZ':'Donghai'
		},
		airline_long_list:{
		    "CI": "China Airlines",
		    "BR": "EVA Air",
		    "B7": "Uni Air",
		    "3U": "Sichuan Airline",
		    "SN": "Brussels Airlines",
		    "ZH": "Shen Zhen Airlines",
		    "CN": "GRAND CHINA AIR",
		    "JS": "Air Koryo",
		    "JD": "Capital Airlines",
		    "9W": "JET AIRWAYS",
		    "AA": "American Airlines",
		    "AB": "Air Berlin",
		    "AC": "Air Canada",
		    "AF": "Air France",
		    "AI": "Air India",
		    "AY": "Finnair",
		    "AZ": "Alitalia",
		    "BA": "Brithish Airways",
		    "BD": "bmi",
		    "BI": "Royal Brunei",
		    "BK": "Ao Kai Airlines",
		    "CA": "AIR CHINA",
		    "CO": "CONTINENTAL AIRLINES",
		    "CX": "Cathay Pacific",
		    "CZ": "CHINA SOUTHERN AIRLINES",
		    "DL": "DELTA AIRLINES",
		    "EK": "Emirates Airline",
		    "EY": "ETIHAD AIRWAYS",
		    "FM": "SHANGHAI AIRLINES",
		    "FV": "Rossiya Airlines",
		    "GA": "Garuda Indonesia",
		    "HU": "Hai Nan Airlines",
		    "HX": "Hong Kong Airlines",
		    "IB": "Iberia",
		    "JL": "Japan Airlines",
		    "KA": "Dragon Air",
		    "KE": "Korean Air",
		    "KL": "Royal Dutch Airlines",
		    "KQ": "Kenya Airways",
		    "LO": "LOT",
		    "LX": "Swiss",
		    "MA": "MALEV",
		    "MF": "Xia Men Airlines",
		    "MH": "Malaysia Airlines",
		    "MI": "SilkAir",
		    "MU": "China Eastern Airlines",
		    "NH": "All Nippon Airways",
		    "NS": "He Bei Airlines",
		    "NW": "Northwest Airlines",
		    "NX": "Air Macau",
		    "NZ": "Air New Zealand",
		    "OM": "MIAT Mongolian Airlines",
		    "OS": "Austrian Airlines",
		    "OZ": "Asiana Airlines",
		    "PG": "Bangkok Airways",
		    "PR": "Philippine Airlines",
		    "QF": "Qantas",
		    "QR": "Qatar Airways",
		    "RJ": "Royal Jordanian",
		    "S7": "S7 Airlines",
		    "SA": "South African Airways",
		    "SC": "Shan Dong Airlines",
		    "SK": "SASS",
		    "SU": "AEROFLOT",
		    "TG": "Thai Airways",
		    "TK": "Turkish Airlines",
		    "TP": "TAP",
		    "UA": "United Airlines",
		    "UL": "SriLankan Airlines",
		    "UM": "Air Zimbabwe",
		    "UN": "Transaero Airlines",
		    "UO": "Hong Kong Express Airways",
		    "US": "US Airways",
		    "VN": "Vietnam Airlines",
		    "VS": "Virgin Atlantic Airways",
		    "XF": "Vladivostok Air",
		    "BE": "Flybe (United Kingdom)",
		    "EI": "AER LINGUS",
		    "JP": "ADRIA AIRWAYS",
		    "KF": "AIR BOTNIA",
		    "MS": "EGYPTAIR",
		    "OU": "CROATIA AIRLINES",
		    "JJ": "TAM LINHAS AEREAS",
		    "A3": "AEGEAN AIRLINES",
		    "OK": "CZECH AIRLINES",
		    "UX": "AIR EUROPA LINEAS AEREAS",
		    "RO": "TAROM",
		    "JR": "Joy Airlines",
		    "PK": "PIA",
		    "ET": "ETHIOPIAN AIRLINES",
		    "KN": "China United Airline",
		    "VD": "He Nan Airlines",
		    "SQ": "Singapore Airlines",
		    "AV": "AVIANCA",
		    "SV": "SAUDIA",
		    "CM": "COPA",
		    "LR": "LACSA",
		    "AM": "Aeromexico",
		    "TA": "TACA International Airline",
		    "AR": "AEROLINEAS ARGENTINAS",
		    "PN": "West AIR",
		    "EU": "CHENG DU AIRLINES",
		    "GS": "Tian Jin Airlines",
		    "HO": "Ji Xiang Airlines",
		    "KY": "Kun Ming Airlines",
		    "8L": "LUCKY AIR",
		    "TV": "Tibet Airlines",
		    "G5": "Hua Xia Airlines",
		    "OQ": "Chong Qing Airlines",
		    "5K": "Fly Guam",
		    "5M": "GM Charter",
		    "AW": "Africa World Airlines",
		    "E8": "City Airways",
		    "K9": "Tonlesap Airlines",
		    "LH": "Lufthansa Airlines",
		    "LA": "LAN-CHILE",
		    "GE": "TRANSASIA AIRWAYS",
			'9C':'Spring Airlines',
		    "LY": "EI AI ISRAEL AIRLINES",
		    "D7": "AirAsia X",
		    "HA":"Hawaiina Airlines"
		},
		aircompany_list:[
			{"value":"A","kw":"A","code":"A"}, 
			{"code":"JP","kw":"ADRIA AIRWAYS","value":"ADRIA AIRWAYS"}, 
			{"code":"A3","kw":"AEGEAN AIRLINES","value":"AEGEAN AIRLINES"}, 
			{"code":"EI","kw":"AER LINGUS","value":"AER LINGUS"}, 
			{"code":"SU","kw":"AEROFLOT","value":"AEROFLOT"}, 
			{"code":"AR","kw":"AEROLINEAS ARGENTINAS","value":"AEROLINEAS ARGENTINAS"}, 
			{"code":"KF","kw":"AIR BOTNIA","value":"AIR BOTNIA"}, 
			{"code":"CA","kw":"AIR CHINA","value":"AIR CHINA"}, 
			{"code":"UX","kw":"AIR EUROPA LINEAS AEREAS","value":"AIR EUROPA LINEAS AEREAS"}, 
			{"code":"AV","kw":"AVIANCA","value":"AVIANCA"}, 
			{"code":"AM","kw":"Aeromexico","value":"Aeromexico"}, 
			{"code":"AW","kw":"Africa World Airlines","value":"Africa World Airlines"}, 
			{"code":"AB","kw":"Air Berlin","value":"Air Berlin"}, 
			{"code":"AC","kw":"Air Canada","value":"Air Canada"}, 
			{"code":"AF","kw":"Air France","value":"Air France"}, 
			{"code":"AI","kw":"Air India","value":"Air India"}, 
			{"code":"JS","kw":"Air Koryo","value":"Air Koryo"}, 
			{"code":"NX","kw":"Air Macau","value":"Air Macau"}, 
			{"code":"NZ","kw":"Air New Zealand","value":"Air New Zealand"}, 
			{"code":"UM","kw":"Air Zimbabwe","value":"Air Zimbabwe"}, 
			{"code":"AZ","kw":"Alitalia","value":"Alitalia"}, 
			{"code":"NH","kw":"All Nippon Airways","value":"All Nippon Airways"}, 
			{"code":"AA","kw":"American Airlines","value":"American Airlines"}, 
			{"code":"BK","kw":"Ao Kai Airlines","value":"Ao Kai Airlines"}, 
			{"code":"OZ","kw":"Asiana Airlines","value":"Asiana Airlines"}, 
			{"code":"OS","kw":"Austrian Airlines","value":"Austrian Airlines"}, 
			{"value":"B","kw":"B","code":"B"}, 
			{"code":"PG","kw":"Bangkok Airways","value":"Bangkok Airways"}, 
			{"code":"BA","kw":"Brithish Airways","value":"Brithish Airways"}, 
			{"code":"SN","kw":"Brussels Airlines","value":"Brussels Airlines"}, 
			{"value":"C","kw":"C","code":"C"}, 
			{"code":"EU","kw":"CHENG DU AIRLINES","value":"CHENG DU AIRLINES"}, 
			{"code":"CZ","kw":"CHINA SOUTHERN AIRLINES","value":"CHINA SOUTHERN AIRLINES"}, 
			{"code":"CO","kw":"CONTINENTAL AIRLINES","value":"CONTINENTAL AIRLINES"}, 
			{"code":"CM","kw":"COPA","value":"COPA"}, 
			{"code":"OU","kw":"CROATIA AIRLINES","value":"CROATIA AIRLINES"}, 
			{"code":"OK","kw":"CZECH AIRLINES","value":"CZECH AIRLINES"}, 
			{"code":"JD","kw":"Capital Airlines","value":"Capital Airlines"}, 
			{"code":"CX","kw":"Cathay Pacific","value":"Cathay Pacific"}, 
			{"code":"CI","kw":"China Airlines","value":"China Airlines"}, 
			{"code":"MU","kw":"China Eastern Airlines","value":"China Eastern Airlines"}, 
			{"code":"KN","kw":"China United Airline","value":"China United Airline"}, 
			{"code":"OQ","kw":"Chong Qing Airlines","value":"Chong Qing Airlines"}, 
			{"code":"E8","kw":"City Airways","value":"City Airways"}, 
			{"value":"D","kw":"D","code":"D"}, 
			{"code":"DL","kw":"DELTA AIRLINES","value":"DELTA AIRLINES"}, 
			{"code":"KA","kw":"Dragon Air","value":"Dragon Air"}, 
			{"value":"E","kw":"E","code":"E"}, 
			{"code":"MS","kw":"EGYPTAIR","value":"EGYPTAIR"}, 
			{"code":"LY","kw":"EI AI ISRAEL AIRLINES","value":"EI AI ISRAEL AIRLINES"}, 
			{"code":"ET","kw":"ETHIOPIAN AIRLINES","value":"ETHIOPIAN AIRLINES"}, 
			{"code":"EY","kw":"ETIHAD AIRWAYS","value":"ETIHAD AIRWAYS"}, 
			{"code":"BR","kw":"EVA Air","value":"EVA Air"}, 
			{"code":"EK","kw":"Emirates Airline","value":"Emirates Airline"}, 
			{"value":"F","kw":"F","code":"F"}, 
			{"code":"AY","kw":"Finnair","value":"Finnair"}, 
			{"code":"5K","kw":"Fly Guam","value":"Fly Guam"}, 
			{"code":"BE","kw":"Flybe United Kingdom","value":"Flybe United Kingdom"}, 
			{"value":"G","kw":"G","code":"G"}, 
			{"code":"5M","kw":"GM Charter","value":"GM Charter"}, 
			{"code":"CN","kw":"GRAND CHINA AIR","value":"GRAND CHINA AIR"}, 
			{"code":"GA","kw":"Garuda Indonesia","value":"Garuda Indonesia"}, 
			{"value":"H","kw":"H","code":"H"}, 
			{"code":"HU","kw":"Hai Nan Airlines","value":"Hai Nan Airlines"}, 
			{"code":"NS","kw":"He Bei Airlines","value":"He Bei Airlines"}, 
			{"code":"VD","kw":"He Nan Airlines","value":"He Nan Airlines"}, 
			{"code":"HX","kw":"Hong Kong Airlines","value":"Hong Kong Airlines"}, 
			{"code":"UO","kw":"Hong Kong Express Airways","value":"Hong Kong Express Airways"}, 
			{"code":"G5","kw":"Hua Xia Airlines","value":"Hua Xia Airlines"}, 
			{"value":"I","kw":"I","code":"I"}, 
			{"code":"IB","kw":"Iberia","value":"Iberia"}, 
			{"value":"J","kw":"J","code":"J"}, 
			{"code":"9W","kw":"JET AIRWAYS","value":"JET AIRWAYS"}, 
			{"code":"JL","kw":"Japan Airlines","value":"Japan Airlines"}, 
			{"code":"HO","kw":"Ji Xiang Airlines","value":"Ji Xiang Airlines"}, 
			{"code":"JR","kw":"Joy Airlines","value":"Joy Airlines"}, 
			{"value":"K","kw":"K","code":"K"}, 
			{"code":"KQ","kw":"Kenya Airways","value":"Kenya Airways"}, 
			{"code":"KE","kw":"Korean Air","value":"Korean Air"}, 
			{"code":"KY","kw":"Kun Ming Airlines","value":"Kun Ming Airlines"}, 
			{"value":"L","kw":"L","code":"L"}, 
			{"code":"LR","kw":"LACSA","value":"LACSA"}, 
			{"code":"LA","kw":"LAN-CHILE","value":"LAN-CHILE"}, 
			{"code":"LO","kw":"LOT","value":"LOT"}, 
			{"code":"8L","kw":"LUCKY AIR","value":"LUCKY AIR"}, 
			{"code":"LH","kw":"Lufthansa Airlines","value":"Lufthansa Airlines"}, 
			{"value":"M","kw":"M","code":"M"}, 
			{"code":"MA","kw":"MALEV","value":"MALEV"}, 
			{"code":"OM","kw":"MIAT Mongolian Airlines","value":"MIAT Mongolian Airlines"}, 
			{"code":"MH","kw":"Malaysia Airlines","value":"Malaysia Airlines"}, 
			{"value":"N","kw":"N","code":"N"}, 
			{"code":"NW","kw":"Northwest Airlines","value":"Northwest Airlines"}, 
			{"value":"P","kw":"P","code":"P"}, 
			{"code":"PK","kw":"PIA","value":"PIA"}, 
			{"code":"PR","kw":"Philippine Airlines","value":"Philippine Airlines"}, 
			{"value":"Q","kw":"Q","code":"Q"}, 
			{"code":"QF","kw":"Qantas","value":"Qantas"}, 
			{"code":"QR","kw":"Qatar Airways","value":"Qatar Airways"}, 
			{"value":"R","kw":"R","code":"R"}, 
			{"code":"FV","kw":"Rossiya Airlines","value":"Rossiya Airlines"}, 
			{"code":"BI","kw":"Royal Brunei","value":"Royal Brunei"}, 
			{"code":"KL","kw":"Royal Dutch Airlines","value":"Royal Dutch Airlines"}, 
			{"code":"RJ","kw":"Royal Jordanian","value":"Royal Jordanian"}, 
			{"value":"S","kw":"S","code":"S"}, 
			{"code":"S7","kw":"S7 Airlines","value":"S7 Airlines"}, 
			{"code":"9C","value":"Spring","kw":"Spring"},  
			{"code":"SK","kw":"SASS","value":"SASS"}, 
			{"code":"SV","kw":"SAUDIA","value":"SAUDIA"}, 
			{"code":"FM","kw":"SHANGHAI AIRLINES","value":"SHANGHAI AIRLINES"}, 
			{"code":"SC","kw":"Shan Dong Airlines","value":"Shan Dong Airlines"}, 
			{"code":"ZH","kw":"Shen Zhen Airlines","value":"Shen Zhen Airlines"}, 
			{"code":"3U","kw":"Sichuan Airline","value":"Sichuan Airline"}, 
			{"code":"MI","kw":"SilkAir","value":"SilkAir"}, 
			{"code":"SQ","kw":"Singapore Airlines","value":"Singapore Airlines"}, 
			{"code":"SA","kw":"South African Airways","value":"South African Airways"}, 
			{"code":"UL","kw":"SriLankan Airlines","value":"SriLankan Airlines"}, 
			{"code":"LX","kw":"Swiss","value":"Swiss"}, 
			{"value":"T","kw":"T","code":"T"}, 
			{"code":"TA","kw":"TACA International Airline","value":"TACA International Airline"}, 
			{"code":"JJ","kw":"TAM LINHAS AEREAS","value":"TAM LINHAS AEREAS"}, 
			{"code":"TP","kw":"TAP","value":"TAP"}, 
			{"code":"RO","kw":"TAROM","value":"TAROM"}, 
			{"code":"GE","kw":"TRANSASIA AIRWAYS","value":"TRANSASIA AIRWAYS"}, 
			{"code":"TG","kw":"Thai Airways","value":"Thai Airways"}, 
			{"code":"GS","kw":"Tian Jin Airlines","value":"Tian Jin Airlines"}, 
			{"code":"TV","kw":"Tibet Airlines","value":"Tibet Airlines"}, 
			{"code":"K9","kw":"Tonlesap Airlines","value":"Tonlesap Airlines"}, 
			{"code":"UN","kw":"Transaero Airlines","value":"Transaero Airlines"}, 
			{"code":"TK","kw":"Turkish Airlines","value":"Turkish Airlines"}, 
			{"value":"U","kw":"U","code":"U"}, 
			{"code":"US","kw":"US Airways","value":"US Airways"}, 
			{"code":"B7","kw":"Uni Air","value":"Uni Air"}, 
			{"code":"UA","kw":"United Airlines","value":"United Airlines"}, 
			{"value":"V","kw":"V","code":"V"}, 
			{"code":"VN","kw":"Vietnam Airlines","value":"Vietnam Airlines"}, 
			{"code":"VS","kw":"Virgin Atlantic Airways","value":"Virgin Atlantic Airways"}, 
			{"code":"XF","kw":"Vladivostok Air","value":"Vladivostok Air"}, 
			{"value":"W","kw":"W","code":"W"}, 
			{"code":"PN","kw":"West AIR","value":"West AIR"}, 
			{"value":"X","kw":"X","code":"X"}, 
			{"code":"MF","kw":"Xia Men Airlines","value":"Xia Men Airlines"}, 
			{"value":"Z","kw":"Z","code":"Z"}, 
			{"code":"BD","kw":"bmi","value":"bmi"}
			]
			/*[
		    {"value":"A","kw":"A","code":"A"}, 
			{"code":"CA","value":"Air China","kw":"Air China"}, 
			{"code":"NH","value":"All Nippon Airways","kw":"All Nippon Airways"}, 
			{"code":"OS","value":"Austrian","kw":"Austrian"},  
			{"value":"C","kw":"C","code":"C"}, 
			{"code":"EU","value":"Chengdu","kw":"Chengdu"}, 
			{"code":"MU","value":"China Eastern","kw":"China Eastern"}, 
			{"code":"G5","value":"China Express","kw":"China Express"}, 
			{"code":"CZ","value":"China Southern","kw":"China Southern"}, 
			{"code":"KN","value":"China United","kw":"China United"}, 
			{"code":"OQ","value":"Chongqing","kw":"Chongqing"}, 
			{"value":"D","kw":"D","code":"D"}, 
			{"code":"JD","value":"Deer Air","kw":"Deer Air"}, 
			{"value":"G","kw":"G","code":"G"}, 
			{"code":"CN","value":"Grand China","kw":"Grand China"}, 
			{"code":"G8","value":"Great Wall","kw":"Great Wall"}, 
			{"code":"GB","value":"Greatwall","kw":"Greatwall"}, 
			{"value":"H","kw":"H","code":"H"}, 
			{"code":"HU","value":"Hainan","kw":"Hainan"}, 
			{"code":"HX","value":"Hongkong","kw":"Hongkong"}, 
			{"code":"UO","value":"Hongkong Express","kw":"Hongkong Express"},
			{"value":"J","kw":"J","code":"J"}, 
			{"code":"HO","value":"Ji Xiang","kw":"Ji Xiang"}, 
			{"code":"JR","value":"Joy Air","kw":"Joy Air"}, 
			{"value":"K","kw":"K","code":"K"}, 
			{"code":"KY","value":"Kunming","kw":"Kunming"}, 
			{"code":"VD","value":"Kunpeng","kw":"Kunpeng"},
			{"value":"N","kw":"N","code":"N"}, 
			{"code":"NS","value":"Northeast","kw":"Northeast"}, 
			{"code":"CJ","value":"Northern","kw":"Northern"}, 
			{"code":"WH","value":"Northwest","kw":"Northwest"}, 
			{"value":"O","kw":"O","code":"O"}, 
			{"code":"BK","value":"OK Air","kw":"OK Air"},
			{"value":"Q","kw":"Q","code":"Q"}, 
			{"code":"QF","value":"Qantas Airways","kw":"Qantas Airways"},
			{"value":"S","kw":"S","code":"S"}, 
			{"code":"SK","value":"Scandinavian","kw":"Scandinavian"}, 
			{"code":"SC","value":"Shandong","kw":"Shandong"}, 
			{"code":"FM","value":"Shanghai","kw":"Shanghai"}, 
			{"code":"8C","value":"Shanxi","kw":"Shanxi"}, 
			{"code":"ZH","value":"Shenzhen","kw":"Shenzhen"}, 
			{"code":"3U","value":"Sichuan","kw":"Sichuan"}, 
			{"code":"SZ","value":"Southwest","kw":"Southwest"}, 
			{"code":"9C","value":"Spring","kw":"Spring"}, 
			{"value":"T","kw":"T","code":"T"}, 
			{"code":"GS","value":"Tianjin","kw":"Tianjin"}, 
			{"code":"TV","value":"Tibet","kw":"Tibet"}, 
			{"value":"W","kw":"W","code":"W"}, 
			{"code":"PN","value":"West Air","kw":"West"}, 
			{"code":"WU","value":"Wuhan","kw":"Wuhan"}, 
			{"value":"X","kw":"X","code":"X"}, 
			{"code":"MF","value":"Xiamen","kw":"Xiamen"}, 
			{"code":"XO","value":"Xinjiang","kw":"Xinjiang"}, 
			{"value":"Y","kw":"Y","code":"Y"}, 
			{"code":"8L","value":"Lucky Air","kw":"Yunnan Lucky"}, 
			{"code":"3Q","value":"Yunnan","kw":"Yunnan"}, 
			{"value":"Z","kw":"Z","code":"Z"}
		  ]*/,
		//政策违背内容列表
		//每项前面可加：Travel policy violated: 
		reasonList : {
			"C001": "Not the lowest fare flight within the travel date",
			"C002": "Not the lowest fare flight within interval of “expected departure time +/- {timeparthour} hours",
			"C003": "Flying duration less than {flighttime} minutes",
			"C004": "Exceeding the latest pre-booking deadline",
			"C005": "Beyond the allowed cabin class",
			"C006": "Not the lowest fare flight within the travel date",
			"C007": "Not the lowest fare flight (of allowed discount) within interval of “expected departure time +/- {timeparthour} hours",
			"C008": "Not the lowest fare flight (of allowed discount) within interval of “departure time of selected flight +/- {timeparthour} hours",
			"C009": "Not the recommended corporate fare"
		},
		//餐食偏好 added by zjf 3-25
		seat_pre:'Seat Preference',
		seat_pre_val:{
			'N':'N/A',
			'NSST':'Standard Seat',
			'NSSA':'Aisle Seat',
			'NSSW':'Window Seat',
		},
		meal_pre:'Meal Preference',
		meal_pre_val:{
			'N':'N/A',
			'AVML':'ASIAN VEG.MEAL',
			'BBML':'INF/BABY FOOD',
			'BLML':'BLAND MEAL',
			'CHML':'CHILD MEAL',
			'DBML':'DIABETIC MEAL',
			'FPML':'FRUIT PLATTER',
			'GFML':'GLUTEN FREE',
			'HNML':'HINDU',
			'KSML':'KOSHER',
			'LCML':'LOW CALORIE',
			'LFML':'LOW CHOLES/FAT',
			'LSML':'LOW SODIUM',
			'MOML':'MUSLIM MEAL',
			'NLML':'NONLACTOSE',
			'RVML':'RAW VEGETARIAN',
			'SFML':'SEAFOOD MEAL',
			'VGML':'VEGETARIAN',
			'VLML':'VEG/LACTO-OVO',
		},
		//餐食偏好 end
	};
	return English;
});
