/**
 * 中文-中国大陆，语言文件
 */
define(function(){
	var Chinese = {
		//常用
		boarding_gate:'登机口',
		Seat_number:'座位号',
		myFlight:'当前航班',
		historyFlight:'飞行历史',
		//航站楼
		Terminal:{
			'001':'北京首都T3',
			'002':'上海虹桥T2'
		},
		Social_seat:'社交选座',
		Partner:'同航班的微信小伙伴:',
		People:'人',
		Seatmap:'座位图',
		Recommended_seat:"为您推荐座位:",
		done:"确定",
		SeatforPartner:'为同行人选座',
		Mayknow:'你可能认识的人',
		flightState:{"到达":"到达","起飞":"起飞","取消":"取消","延误":"延误","计划":"计划","无":"无","":"无"},
		sameCabinAlert:'您已经预定了相同的行程的共享航班',
	
		//舱位类型
		cabinType:{'A':'全部','F':'头等舱','C':'商务舱','Y':'经济舱','0':'经济舱'},//0:超级经济舱
		selectCabin:'选择舱位',
		//周
		week:['周日','周一','周二','周三','周四','周五','周六'],
		short_week:['周日','周一','周二','周三','周四','周五','周六'],
		hotelshort_week:['周日','周一','周二','周三','周四','周五','周六'],
		ok:'确定',
		cancel:'取消',
		//航空公司
		airline_list:{
			'3U':'川航',
			'8C':'山西航',
			'8L':'祥鹏',
			'CA':'国航',
			'9C':'春秋',
			'CN':'大新华',
			'CZ':'南航',
			'EU':'成都航',
			'FM':'上航',
			'G8':'长城',
			'HO':'吉祥',
			'HU':'海航',
			'JD':'金鹿',
			'JR':'幸福',
			'KN':'中联航',
			'MF':'厦航',
			'MU':'东航',
			'SC':'山东航',
			'SZ':'西南航',
			'WH':'西北航',
			'WU':'武汉航',
			'XO':'新疆航',
			'ZH':'深航',
			'PN':'西部航',
			'BK':'奥凯',
			'G5':'华夏',
			'GS':'天津',
			'KY':'昆明',
			'TV':'西藏',
			'CJ':'北方',
			'3Q':'云南',
			'GB':'长城',
			'NS':'东北',
			'OQ':'重庆',
			'VD':'鲲鹏',
		    'HX':'香港',
		    'DZ':'东海'
		},
		airline_long_list:{
		    "CI": "中华航空",
		    "BR": "长荣航空",
		    "B7": "立荣航空",
		    "3U": "四川航空",
		    "SN": "比利时世界航空",
		    "ZH": "深圳航空",
		    "CN": "大新华航空",
		    "JS": "朝鲜航空",
		    "JD": "首都航空",
		    "9W": "喷气机航空",
		    "AA": "美国航空",
		    "AB": "柏林航空",
		    "AC": "加拿大航空",
		    "AF": "法国航空",
		    "AI": "印度航空",
		    "AY": "芬兰航空",
		    "AZ": "意大利航空",
		    "BA": "英国航空",
		    "BD": "英国中部航空",
		    "BI": "文莱王家航空",
		    "BK": "奥凯航空",
		    "CA": "国航",
		    "CO": "大陆航空",
		    "CX": "国泰航空",
		    "CZ": "南方航空",
		    "DL": "达美航空",
		    "EK": "阿联酋航空",
		    "EY": "阿提哈德航空",
		    "FM": "上海航空",
		    "FV": "天巡",
		    "GA": "印度尼西亚航空",
		    "HU": "海南航空",
		    "HX": "香港航空",
		    "IB": "西班牙航空",
		    "JL": "日本航空",
		    "KA": "港龙航空",
		    "KE": "大韩航空",
		    "KL": "荷兰皇家航空",
		    "KQ": "肯尼亚航空",
		   
		    "LO": "波兰航空",
		    "LX": "克罗斯航空",
		    "MA": "匈牙利航空",
		    "MF": "厦门航空",
		    "MH": "马来西亚航空",
		    "MI": "丝绸航空",
		    "MU": "东方航空",
		    "NH": "全日空航空",
		    "NS": "河北航空",
		    "NW": "美国西北航空",
		    "NX": "澳门航空",
		    "NZ": "新西兰航空",
		    "OM": "蒙古航空",
		    "OS": "奥地利航空",
		    "OZ": "韩亚航空",
		    "PG": "曼谷航空",
		    "PR": "菲律宾航空",
		    "QF": "澳洲航空",
		    "QR": "卡塔尔航空",
		    "RJ": "约旦王家航空",
		    "S7": "西伯利亚(S7)航空",
		    "SA": "南非航空",
		    "SC": "山东航空",
		    "SK": "北欧航空",
		    "SU": "俄罗斯航空",
		    "TG": "泰国航空",
		    "TK": "土耳其航空",
		    "TP": "葡萄牙航空",
		    "UA": "美联航",
		    "UL": "兰卡航空",
		    "UM": "津巴布韦航空",
		    "UN": "俄洲际航空",
		    "UO": "香港快运航空",
		    "US": "合众国航空",
		    "VN": "越南航空",
		    "VS": "维珍航空",
		    "XF": "海参崴航空",
		    "BE": "Flybe航空",
		    "EI": "爱尔兰航空",
		    "JP": "亚得利亚航空",
		    "KF": "博特尼亚航空",
		    "MS": "埃及航空",
		    "OU": "克罗地亚航空",
		    "JJ": "巴西塔姆航空",
		    "A3": "爱琴海航空",
		    "OK": "捷克斯洛伐克航空",
		    "UX": "西班牙欧洲航空",
		    "RO": "罗马尼亚航空",
		    "JR": "幸福航空",
		    "PK": "巴基斯坦航空",
		    "ET": "埃塞俄比亚航空",
		    "KN": "中联航",
		    "VD": "河南航空",
		    "SQ": "新加坡航空",
		    "AV": "哥伦比亚国家航空",
		    "SV": "沙特阿拉伯航空",
		    "CM": "巴拿马航空",
		    "LR": "哥斯达黎加航空",
		    "AM": "墨西哥航空",
		    "TA": "塔卡航空",
		    "AR": "阿根廷航空",
		    "PN": "西部航空",
		    "EU": "成都航空",
		    "GS": "天津航空",
		    "HO": "上海吉祥航空",
		    "KY": "昆明航空",
		    "8L": "云南祥鹏航空",
		    "TV": "西藏航空",
		    "G5": "华夏航空",
		    "OQ": "重庆航空",
		    "5K": "美国关岛航空",
		    "5M": "美佳包机",
		    "AW": "非洲加纳",
		    "E8": "泰国城市航空",
		    "K9": "柬埔寨通里萨航空",
		    "LH": "德国汉莎航空",
		    "LA": "智利国家航空",
		    "GE": "复兴航空",
			'9C':'春秋航空',
		    "LY": "以色列航空",
		    "D7": "亚洲航空",
		    "HA":"夏威夷航空"
		},
		aircompany_list:[
			{"value":"A","kw":"A","code":"A"}, 
			{"code":"AR","kw":"Agentinghangkong","value":"阿根廷航空"}, 
			{"code":"EI","kw":"Aierlanhangkong","value":"爱尔兰航空"}, 
			{"code":"MS","kw":"Aijihangkong","value":"埃及航空"}, 
			{"code":"A3","kw":"Aiqinhaihangkong","value":"爱琴海航空"}, 
			{"code":"ET","kw":"Aisaiebiyahangkong","value":"埃塞俄比亚航空"}, 
			{"code":"EK","kw":"Alianqiuhangkong","value":"阿联酋航空"}, 
			{"code":"OS","kw":"Aodilihangkong","value":"奥地利航空"}, 
			{"code":"BK","kw":"Aokaihangkong","value":"奥凯航空"}, 
			{"code":"NX","kw":"Aomenhangkong","value":"澳门航空"}, 
			{"code":"QF","kw":"Aozhouhangkong","value":"澳洲航空"}, 
			{"code":"EY","kw":"Atihadehangkong","value":"阿提哈德航空"}, 
			{"value":"B","kw":"B","code":"B"}, 
			{"code":"PK","kw":"Bajisitanhangkong","value":"巴基斯坦航空"}, 
			{"code":"CM","kw":"Banamahangkong","value":"巴拿马航空"}, 
			{"code":"JJ","kw":"Baxitamuhangkong","value":"巴西塔姆航空"}, 
			{"code":"JD","kw":"Beijingshoudouhangkong","value":"首都航空"}, 
			{"code":"SK","kw":"Beiouhangkong","value":"北欧航空"}, 
			{"code":"SN","kw":"Bilishishijiehangkong","value":"比利时世界航空"}, 
			{"code":"LO","kw":"Bolanhangkong","value":"波兰航空"}, 
			{"code":"AB","kw":"Bolinhangkong","value":"柏林航空"}, 
			{"code":"KF","kw":"Boteniyahangkong","value":"博特尼亚航空"}, 
			{"value":"C","kw":"C","code":"C"}, 
			{"code":"JS","kw":"Chaoxianhangkong","value":"朝鲜航空"}, 
			{"code":"EU","kw":"Chengdouhangkong","value":"成都航空"},
			{"code":"9C","value":"春秋航空","kw":"Chunqiuhangkong"},  
			{"value":"D","kw":"D","code":"D"}, 
			{"code":"KE","kw":"Dahanhangkong","value":"大韩航空"}, 
			{"code":"CO","kw":"Daluhangkong","value":"大陆航空"}, 
			{"code":"DL","kw":"Dameihangkong","value":"达美航空"}, 
			{"code":"CN","kw":"Daxinhuahangkong","value":"大新华航空"}, 
			{"code":"LH","kw":"Deguohanshahangkong","value":"德国汉莎航空"}, 
			{"code":"LX","kw":"Deluosihangkong","value":"克罗斯航空"}, 
			{"code":"KQ","kw":"Denniyahangkong","value":"肯尼亚航空"}, 
			{"code":"MU","kw":"Dongfanghangkong","value":"东方航空"}, 
			{"value":"E","kw":"E","code":"E"}, 
			{"code":"SU","kw":"Eluosihangkong","value":"俄罗斯航空"}, 
			{"code":"UN","kw":"Eluosizhoujihangkong","value":"俄洲际航空"}, 
			{"value":"F","kw":"F","code":"F"}, 
			{"code":"AF","kw":"Faguohangkong","value":"法国航空"}, 
			{"code":"PR","kw":"Feilu:binhangkong","value":"菲律宾航空"}, 
			{"code":"AW","kw":"Feizhoujiana","value":"非洲加纳"}, 
			{"code":"AY","kw":"Fenlanhangkong","value":"芬兰航空"}, 
			{"code":"BE","kw":"Flybehangkong","value":"Flybe航空"}, 
			{"code":"GE","kw":"Fuxinghangkong","value":"复兴航空"}, 
			{"value":"G","kw":"G","code":"G"}, 
			{"code":"KA","kw":"Ganglonghangkong","value":"港龙航空"}, 
			{"code":"AV","kw":"Gelunbiyaguojiahangkong","value":"哥伦比亚国家航空"}, 
			{"code":"LR","kw":"Gesidalijiahangkong","value":"哥斯达黎加航空"}, 
			{"code":"NH","kw":"Guanrikonghangkong","value":"全日空航空"}, 
			{"code":"CA","kw":"Guohang","value":"国航"}, 
			{"code":"CX","kw":"Guotaihangkong","value":"国泰航空"}, 
			{"value":"H","kw":"H","code":"H"}, 
			{"code":"XF","kw":"Haicanweihangkong","value":"海参崴航空"}, 
			{"code":"HU","kw":"Hainanhangkong","value":"海南航空"}, 
			{"code":"OZ","kw":"Hanyahangkong","value":"韩亚航空"}, 
			{"code":"NS","kw":"Hebeihangkong","value":"河北航空"}, 
			{"code":"KL","kw":"Helanhuangjiahangkong","value":"荷兰皇家航空"}, 
			{"code":"VD","kw":"Henanhangkong","value":"河南航空"}, 
			{"code":"US","kw":"Hezhongguohangkong","value":"合众国航空"}, 
			{"code":"G5","kw":"Huaxiahangkong","value":"华夏航空"}, 
			{"value":"J","kw":"J","code":"J"}, 
			{"code":"AC","kw":"Jianadahangkong","value":"加拿大航空"}, 
			{"code":"K9","kw":"Jianpuzhaitonglisahangkong","value":"柬埔寨通里萨航空"}, 
			{"code":"OK","kw":"Jiekesiluofakehangkong","value":"捷克斯洛伐克航空"}, 
			{"code":"UM","kw":"Jinbabuweihangkong","value":"津巴布韦航空"}, 
			{"value":"K","kw":"K","code":"K"}, 
			{"code":"QR","kw":"Kataerhangkong","value":"卡塔尔航空"}, 
			{"code":"OU","kw":"Keluodiyahangkong","value":"克罗地亚航空"}, 
			{"code":"KY","kw":"Kunminghangkong","value":"昆明航空"}, 
			{"value":"L","kw":"L","code":"L"}, 
			{"code":"UL","kw":"Lankahangkong","value":"兰卡航空"}, 
			{"code":"B7","kw":"Lironghangkong","value":"立荣航空"}, 
			{"code":"RO","kw":"Luomaniyahangkong","value":"罗马尼亚航空"}, 
			{"value":"M","kw":"M","code":"M"}, 
			{"code":"MH","kw":"Malaixiyahangkong","value":"马来西亚航空"}, 
			{"code":"PG","kw":"Manguhangkong","value":"曼谷航空"}, 
			{"code":"5K","kw":"Meiguoguandaohangkong","value":"美国关岛航空"}, 
			{"code":"AA","kw":"Meiguohangkong","value":"美国航空"}, 
			{"code":"UA","kw":"Meiguolianhehangkong","value":"美联航"}, 
			{"code":"NW","kw":"Meiguoxibeihangkong","value":"美国西北航空"}, 
			{"code":"5M","kw":"Meijiabaoji","value":"美佳包机"}, 
			{"code":"OM","kw":"Mengguhangkong","value":"蒙古航空"}, 
			{"code":"AM","kw":"Moxigehangkong","value":"墨西哥航空"}, 
			{"value":"N","kw":"N","code":"N"}, 
			{"code":"CZ","kw":"Nanfanghangkong","value":"南方航空"}, 
			{"code":"SA","kw":"Nanfeihangkong","value":"南非航空"},
			{"value":"P","kw":"P","code":"P"}, 
			{"code":"9W","kw":"Penqijihangkong","value":"喷气机航空"}, 
			{"code":"TP","kw":"Putaoyahangkong","value":"葡萄牙航空"},
			{"value":"R","kw":"R","code":"R"}, 
			{"code":"JL","kw":"Ribenhangkong","value":"日本航空"}, 
			{"value":"S","kw":"S","code":"S"}, 
			{"code":"MF","kw":"Shamenhangkong","value":"厦门航空"}, 
			{"code":"SC","kw":"Shandonghangkong","value":"山东航空"}, 
			{"code":"FM","kw":"Shanghaihangkong","value":"上海航空"}, 
			{"code":"HO","kw":"Shanghaijixianghangkong","value":"上海吉祥航空"}, 
			{"code":"SV","kw":"Shatealabohangkong","value":"沙特阿拉伯航空"}, 
			{"code":"ZH","kw":"Shenzhenhangkong","value":"深圳航空"}, 
			{"code":"MI","kw":"Sichouhangkong","value":"丝绸航空"}, 
			{"code":"3U","kw":"Sichuanhangkong","value":"四川航空"}, 
			{"value":"T","kw":"T","code":"T"}, 
			{"code":"E8","kw":"Taiguochengshihangkong","value":"泰国城市航空"}, 
			{"code":"TG","kw":"Taiguohangkong","value":"泰国航空"}, 
			{"code":"TA","kw":"Takahangkong","value":"塔卡航空"}, 
			{"code":"GS","kw":"Tianjinhangkong","value":"天津航空"}, 
			{"code":"FV","kw":"Tianxun","value":"天巡"}, 
			{"code":"TK","kw":"Tuerqihangkong","value":"土耳其航空"},
			{"value":"W","kw":"W","code":"W"}, 
			{"code":"VS","kw":"Weizhenhangkong","value":"维珍航空"}, 
			{"code":"BI","kw":"Wenlaiwangjiahangkong","value":"文莱王家航空"}, 
			{"value":"X","kw":"X","code":"X"}, 
			{"code":"HX","kw":"Xiangganghangkong","value":"香港航空"}, 
			{"code":"UO","kw":"Xianggangkuaiyunhangkong","value":"香港快运航空"}, 
			{"code":"IB","kw":"Xibanyahangkong","value":"西班牙航空"}, 
			{"code":"UX","kw":"Xibanyaouzhouhangkong","value":"西班牙欧洲航空"}, 
			{"code":"S7","kw":"Xiboliya(S7)hangkong","value":"西伯利亚(S7)航空"}, 
			{"code":"PN","kw":"Xibuhangkong","value":"西部航空"}, 
			{"code":"JR","kw":"Xingfuhangkong","value":"幸福航空"}, 
			{"code":"SQ","kw":"Xinjiapohangkong","value":"新加坡航空"}, 
			{"code":"NZ","kw":"Xinxilanhangkong","value":"新西兰航空"}, 
			{"code":"MA","kw":"Xiongyalihangkong","value":"匈牙利航空"}, 
			{"code":"TV","kw":"Xizanghangkong","value":"西藏航空"}, 
			{"value":"Y","kw":"Y","code":"Y"}, 
			{"code":"JP","kw":"Yadeliyahangkong","value":"亚得利亚航空"}, 
			{"code":"AZ","kw":"Yidalihangkong","value":"意大利航空"}, 
			{"code":"AI","kw":"Yinduhangkong","value":"印度航空"}, 
			{"code":"GA","kw":"Yindunixiyahangkong","value":"印度尼西亚航空"}, 
			{"code":"BA","kw":"Yingguohangkong","value":"英国航空"}, 
			{"code":"BD","kw":"Yingguozhongbuhangkong","value":"英国中部航空"}, 
			{"code":"LY","kw":"Yiseliehangkong","value":"以色列航空"}, 
			{"code":"RJ","kw":"Yuedanwangjiahangkong","value":"约旦王家航空"}, 
			{"code":"VN","kw":"Yuenanhangkong","value":"越南航空"}, 
			{"code":"8L","kw":"Yunnanxiangpenghangkong","value":"云南祥鹏航空"}, 
			{"value":"Z","kw":"Z","code":"Z"}, 
			{"code":"BR","kw":"Zhangronghangkong","value":"长荣航空"}, 
			{"code":"LA","kw":"Zhiliguojiahangkong","value":"智利国家航空"}, 
			{"code":"CI","kw":"Zhonghuahangkong","value":"中华航空"}, 
			{"code":"KN","kw":"Zhonglianhang","value":"中联航"}, 
			{"code":"OQ","kw":"Zhongqinghangkong","value":"重庆航空"}
			]
			/*[
			{"value":"A","kw":"A","code":"A"}, 
			{"code":"OS","value":"奥地利","kw":"Adlhk"}, 
			{"code":"BK","value":"奥凯航空","kw":"Ak"}, 
			{"code":"QF","value":"澳洲航空","kw":"Azhk"}, 
			{"value":"B","kw":"B","code":"B"}, 
			{"code":"CJ","value":"北方航空","kw":"Bfhk"}, 
			{"code":"SK","value":"北欧航空","kw":"Bohk"}, 
			{"value":"C","kw":"C","code":"C"}, 
			{"code":"G8","value":"长城航空","kw":"Cc"}, 
			{"code":"GB","value":"长城航空","kw":"Cchk"}, 
			{"code":"EU","value":"成都航空","kw":"Cd"}, 
			{"code":"3U","value":"川航","kw":"Ch"}, 
			{"code":"9C","value":"春秋航空","kw":"Cq"}, 
			{"code":"OQ","value":"重庆航空","kw":"Cqhk"}, 
			{"value":"D","kw":"D","code":"D"}, 
			{"code":"NS","value":"东北航空","kw":"Dbhk"}, 
			{"code":"MU","value":"东航","kw":"Dh"}, 
			{"code":"CN","value":"大新华","kw":"Dxh"}, 
			{"value":"G","kw":"G","code":"G"}, 
			{"code":"CA","value":"国航","kw":"Gh"}, 
			{"code":"UO","value":"港联航空","kw":"Glhk"}, 
			{"value":"H","kw":"H","code":"H"}, 
			{"code":"HU","value":"海航","kw":"Hh"}, 
			{"code":"G5","value":"华夏航空","kw":"Hxhk"},
			{"value":"J","kw":"J","code":"J"}, 
			{"code":"JD","value":"金鹿航空","kw":"Jl"}, 
			{"code":"HO","value":"吉祥航空","kw":"Jx"}, 
			{"value":"K","kw":"K","code":"K"}, 
			{"code":"KY","value":"昆明航空","kw":"Kmhk"}, 
			{"code":"VD","value":"鲲鹏航空","kw":"Kphk"}, 
			{"value":"N","kw":"N","code":"N"}, 
			{"code":"CZ","value":"南航","kw":"Nh"}, 
			{"value":"Q","kw":"Q","code":"Q"}, 
			{"code":"NH","value":"全日空","kw":"Qrkhk"},
			{"value":"S","kw":"S","code":"S"}, 
			{"code":"SC","value":"山东航空","kw":"Sdhk"}, 
			{"code":"FM","value":"上航","kw":"Sh"}, 
			{"code":"8C","value":"山西航空","kw":"Sx"}, 
			{"code":"ZH","value":"深航","kw":"Szhk"}, 
			{"value":"T","kw":"T","code":"T"}, 
			{"code":"GS","value":"天津航空","kw":"Tjhk"}, 
			{"value":"W","kw":"W","code":"W"}, 
			{"code":"WU","value":"武汉航空","kw":"Whhk"}, 
			{"value":"X","kw":"X","code":"X"}, 
			{"code":"WH","value":"西北航空","kw":"Xbhk"}, 
			{"code":"PN","value":"西部航空","kw":"Xbhk"}, 
			{"code":"JR","value":"幸福航空","kw":"Xf"}, 
			{"code":"HX","value":"香港航空","kw":"Xghk"}, 
			{"code":"MF","value":"厦航","kw":"Xh"}, 
			{"code":"XO","value":"新疆航空","kw":"Xjhk"}, 
			{"code":"SZ","value":"西南航空","kw":"Xnhk"}, 
			{"code":"8L","value":"祥鹏航空","kw":"Xp"}, 
			{"code":"TV","value":"西藏航空","kw":"Xzhk"}, 
			{"value":"Y","kw":"Y","code":"Y"}, 
			{"code":"3Q","value":"云南航空","kw":"Ynhk"}, 
			{"value":"Z","kw":"Z","code":"Z"}, 
			{"code":"KN","value":"中联航","kw":"Zlh"}
		  ]*/,
		
		//餐食偏好 added by zjf 3-25
		seat_pre:'座位偏好',
		seat_pre_val:{
			'N':'无',
			'NSST':'普通座位',
			'NSSA':'靠过道座位',
			'NSSW':'靠窗座位',
		},
		meal_pre:'餐食偏好',
		meal_pre_val:{
			'N':'无',
			'AVML':'亚洲素餐',
			'BBML':'婴儿餐',
			'BLML':'清淡餐食',
			'CHML':'儿童餐',
			'DBML':'糖尿病患者餐',
			'FPML':'水果拼盘',
			'GFML':'无麦麸餐',
			'HNML':'印度餐食',
			'KSML':'犹太教餐',
			'LCML':'低卡卢里餐食',
			'LFML':'低脂肪/胆固醇餐',
			'LSML':'低盐餐食',
			'MOML':'穆斯林餐食',
			'NLML':'无乳糖餐',
			'RVML':'原质餐(稍加烹饪素餐)',
			'SFML':'海鲜餐',
			'VGML':'素食',
			'VLML':'奶素食',
		},
		//餐食偏好 end
		
	}
	return Chinese;
});
